const fs=require("node:fs"),vm=require("node:vm"),assert=require("node:assert/strict");
const code=fs.readFileSync(__dirname+"/capture.js","utf8");
const events=[];let tick,visibleTitle="Video A";
const metadata={title:"Video A",artist:"Artist A",artwork:[{src:"https://images.example.org/small.jpg",sizes:"150x83"},{src:"https://images.example.org/large.jpg",sizes:"1280x720"}]};
const media={ended:false,paused:false,readyState:4,poster:"",currentTime:12,duration:240,playbackRate:1};const location={hostname:"www.youtube.com",pathname:"/watch",href:"https://www.youtube.com/watch?v=abcdefghijk"};
let now=1791453745000;const clock={now:()=>now};
let elements=[media];
const context={window:{dispatchEvent:event=>events.push(JSON.parse(event.detail))},document:{querySelectorAll:()=>elements,querySelector:()=>({textContent:visibleTitle})},navigator:{mediaSession:{metadata}},location,URL,Date:clock,CustomEvent:class{constructor(name,options){this.detail=options.detail;}},setInterval:fn=>tick=fn};
vm.runInNewContext(code,context);assert.equal(events.length,1);assert.equal(events[0].youtubeVideoId,"abcdefghijk");assert.equal(events[0].artwork[0],"https://images.example.org/large.jpg");
tick();assert.equal(events.length,1);
assert.equal(events[0].elapsedSeconds,12);assert.equal(events[0].playing,true);assert.equal(events[0].durationSeconds,240);
now+=500;media.currentTime=12.5;tick();assert.equal(events.length,1);
location.href="https://www.youtube.com/watch?v=lmnopqrstuv";visibleTitle="Video B";tick();assert.equal(events.length,1);
metadata.title="Video B";tick();assert.equal(events[1].youtubeVideoId,"lmnopqrstuv");assert.equal(events[1].title,"Video B");
location.hostname="player.example.org";location.pathname="/music";metadata.title="Song C";metadata.artist="Artist C";tick();assert.equal(events[2].youtubeVideoId,"");assert.equal(events[2].title,"Song C");
media.paused=true;tick();assert.equal(events.at(-1).playing,false);
const pauseCount=events.length;now+=1000;tick();assert.equal(events.length,pauseCount+1);assert.equal(events.at(-1).elapsedSeconds,12.5);
media.currentTime=90;tick();assert.equal(events.at(-1).elapsedSeconds,90);
media.paused=false;media.playbackRate=2;tick();assert.equal(events.at(-1).playbackRate,2);
media.duration=Infinity;now+=1000;tick();assert.equal(events.at(-1).durationSeconds,0);
media.ended=true;metadata.title="Ended";tick();assert.equal(events.at(-1).ended,true);
media.ended=false;const beforeAmbiguous=events.length;elements=[media,{...media}];now+=1000;tick();assert.equal(events.length,beforeAmbiguous);
elements=[{...media,paused:true},media];tick();assert.equal(events.length,beforeAmbiguous+1);assert.equal(events.at(-1).elapsedSeconds,90);
const manifest=JSON.parse(fs.readFileSync(__dirname+"/manifest.json","utf8"));
assert(!manifest.permissions.includes("history")&&!manifest.permissions.includes("tabs")&&!manifest.permissions.includes("cookies"));
assert.deepEqual(manifest.host_permissions,["http://127.0.0.1/*"]);
console.log("BROWSER_CAPTURE_OK metadata/artwork/navigation; real media progress, 1s heartbeat, immediate pause/seek/rate/end, live-stream unknown duration; optional-site-access");
