# Generate compact calendar facts through the public .NET calendar API, not copied source.
$calendar = [Globalization.ChineseLunisolarCalendar]::new()
$rows = for ($year = 1901; $year -le 2100; $year++) {
    $leap = $calendar.GetLeapMonth($year)
    $bits = 0
    for ($month = 1; $month -le $calendar.GetMonthsInYear($year); $month++) {
        if ($calendar.GetDaysInMonth($year, $month) -eq 30) { $bits = $bits -bor (1 -shl ($month - 1)) }
    }
    $start = $calendar.ToDateTime($year,1,1,0,0,0,0)
    $offset = ($start - [datetime]::new($year,1,1)).Days
    '    0x{0:X6}u, // {1}' -f (($offset -shl 17) -bor ($bits -shl 4) -bor $leap),$year
}
$content = "#pragma once`n#include <stdint.h>`n// Calendar facts generated by scripts/generate_lunar_calendar.ps1 using .NET.`n// Bits: leap month ordinal [0..3], 30-day month flags [4..16], new year day offset [17..22].`nnamespace LunarCalendar {`nstatic constexpr uint32_t Years[] = {`n" + ($rows -join "`n") + "`n};`n}`n"
[IO.File]::WriteAllText((Join-Path $PSScriptRoot '../firmware/include/LunarCalendarData.h'), $content, [Text.UTF8Encoding]::new($false))
